### ISSUE TITLE
Vagrant up error

### ISSUE THREAD

**Issue by thanhson1085** [ClusterHQ/marathon-flocker-plugin-demo#2]
I try to follow your tutorial. If i use Git Bash Terminal, I got an error as below:

```
My PC@MYPC /f/Vagrant/marathon-flocker-plugin-demo (master)
$ vagrant up
Bringing machine 'node1' up with 'virtualbox' provider...
Bringing machine 'node2' up with 'virtualbox' provider...
==> node1: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter #8",
"--ip", "172.16.79.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage.exe: error: The host network interface with the given name co
uld not be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWr
ap, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).ra
w(), hif.asOutParam())" at line 204 of file VBoxManageHostonly.cpp

```

If I use CMD, I got an error as below:

```
==> node2: ##################################################################
==> node2: #################### Installing mesosphere  #########
==> node2: ##################################################################
==> node2: /vagrant/mesosphere-install.sh: line 6: $'\r': command not found
==> node2: /vagrant/mesosphere-install.sh: line 11: $'\r': command not found
==> node2: /vagrant/mesosphere-install.sh: line 12: syntax error near unexpec
'=> node2: /vagrant/mesosphere-install.sh: line 12: `setup-master() {
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

**Comment by binocarlos** [comment]
@thanhson1085 Hey, thanks for your bug report...

I'm assuming that you are using GIT on Windows.  It is better to use the normal command line i.e. CMD rather than the Git BASH terminal.

With regard to the CMD version error - I think what is happening is that when you installed GIT for windows it gave you the following options:
- Checkout Windows-style, commit Unix-style line endings Git will convert LF to CRLF when checking out text files. When committing text files, CRLF will be converted to LF. For cross-platform projects, this is the recommended setting on Windows ("core.autocrlf" is set to "true")
- Checkout as-is, commit Unix-style line endings Git will not perform any conversion when checking out text files. When committing text files, CRLF will be converted to LF. For cross-platform projects this is the recommended setting on Unix ("core.autocrlf" is set to "input").
- Checkout as-is, commit as-is Git will not perform any conversions when checking out or committing text files. Choosing this option is not recommended for cross-platform projects ("core.autocrlf" is set to "false")

So - I'm assuming you choose the first option i.e. convert line endings to windows and commit back as unix.

The problem here is that the windows line endings are then being passed into a Linux environment (i.e. inside the Vagrant VM) and this is then breaking the bash script.

The clue is in the line `line 6: $'\r': command not found` - where `\r` is a windows line ending that should not be there.

I have just pushed a `.gitattributes` file that will keep the unix line endings upon checkout.

Can you please first do a `vagrant destroy -f` (from inside the repo).

Then remove the folder.

Then re-clone the repo (where it will preserve the unix line endings) and try doing the walk-though again.
We have just tested this on Windows and replicated your error - with the new commit it fixed the problem.

Many thanks for this bug report - it was an issue we were unaware of and I have made the same fix to our other repositories...

Let me know if this works for you!

**Comment by thanhson1085** [comment]
Thanks for your support. 
The reason of the issue is I am using a out-of-date Git version in Windows. I re-installed my Git and re-clone your code. It works properly.

**Comment by binocarlos** [comment]
@thanhson1085 great! thanks for the bug-report though - it prompted us to add `.gitattributes` to the repos from now on
